#pragma once

#include <vector>
#include <string>

// Code generated by 'conan new cmake-exe ...'
void cadance();
void cadance_print_vector(const std::vector<std::string> &strings);

// namespace for this zeroth variant of cadance.
// Enabales a later first namespace in case we need to refactor
// from zeroth to first while keeping both 'alive' but separate
namespace zeroth {
  int main(int argc, char* argv[]);
}
