#include <iostream>
#include <vector>
#include <string>
#include "cadance.h"
#include "tests/tests.hpp"

int main(int argc, char* argv[]) {

#ifdef CADANCE_VERSION 
    std::cout << "Cadance Version: " << CADANCE_VERSION << std::endl;
#else
    std::cout << "Cadance Version: ??" << std::endl;
#endif

    if (argc==2 and std::string{argv[1]} == "-test") {
        return test::run_all();
    }

    // shoe horne in conan package manager test code (just to keep it for now)
    if (true) {
        // Code generated by 'conan new cmake-exe ...'
        cadance();
        std::vector<std::string> vec;
        vec.push_back("test_package");
        cadance_print_vector(vec);
        // End of conan generated code
    }

    int result{};
    while (true) {
        if (result = zeroth::main(argc,argv);result == 0) break;
    }
    return result;
}
